# Array Constructor Examples

In [1]:
# Imports required but not shown in the video lecture.
from numpy import array, float32, uint8, frombuffer

## Array Consturctor Examples
### FLOATING POINT ARRAYS
Default to double precision

In [2]:
a = array([0, 1.0, 2, 3])
a.dtype

dtype('float64')

In [3]:
a.nbytes

32

### REDUCING PRECISION

In [4]:
a = array([0, 1., 2, 3], dtype=float32)
a.dtype

dtype('float32')

In [5]:
a.nbytes

16

### UNSIGNED INTEGER BYTE

In [6]:
a = array([0, 1, 2, 3], dtype=uint8)
a.dtype

dtype('uint8')

In [7]:
a.nbytes

4

### ARRAY FROM BINARY DATA
frombuffer or fromfile to create and array from binary data.

In [8]:
a = frombuffer('foo', dtype=uint8)
a

array([102, 111, 111], dtype=uint8)

Reverse operation

In [9]:
a.tofile('foo.dat')

### Live Demo

In [10]:
ord('f')

102

In [11]:
ord('o')

111

### Back to Slide

## NumPy dtypes (see video)

### Live Demo

In [12]:
ary = array([1, 1.2, 'hello', [10, 20, 30]], dtype=object)

In [13]:
ary

array([1, 1.2, 'hello', [10, 20, 30]], dtype=object)

In [14]:
ary[0]

1

In [15]:
ary[1]

1.2

In [16]:
ary[2]

'hello'

In [17]:
ary * 2

array([2, 2.4, 'hellohello', [10, 20, 30, 10, 20, 30]], dtype=object)

In [18]:
ary + ary

array([2, 2.4, 'hellohello', [10, 20, 30, 10, 20, 30]], dtype=object)

### Back to Slide

## NumPy dtypes (see video)

Copyright 2008-2016, Enthought, Inc.<br>Use only permitted under license.  Copying, sharing, redistributing or other unauthorized use strictly prohibited.<br>http://www.enthought.com