# Choose

In [8]:
# Imports required but not shown in the video lecture.
from numpy import array, empty, int32, choose,shape

## Choose (switch statement)
How do you implement a "switch", "case", or "multiplexer" with arrays?

### Switch using for loop
"Switch" conditions using a for loop.

In [2]:
control = array([[1, 0, 1],
                 [2, 1, 0],
                 [1, 2, 2]])

M, N = control.shape
output = empty((M, N), int32)

for i in range(M):
    for j in range(N):
        if control[i, j] == 0:
            output[i, j] = 10
        elif control[i, j] == 1:
            output[i, j] = 11
        elif control[i, j] == 2:
            output[i, j] = 12
        else:
            raise IndexError()

`choose` acts like a "switch" selecting between multiple choices.

In [3]:
output = choose(control, (10, 11, 12))
output

array([[11, 10, 11],
       [12, 11, 10],
       [11, 12, 12]])

Choose for an array of arguments:

In [4]:
i_0 = array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8]])

i_2 = array([[20, 21, 22],
             [23, 24, 25],
             [26, 27, 28]])

output = choose(control, (i_0, 10, i_2))
output

array([[10,  1, 10],
       [23, 10,  5],
       [10, 27, 28]])

## Example - `choose()`
### Clip lower values to 10

In [5]:
a = array([[0, 1, 2],
           [10, 11, 12],
           [20, 21, 22]])
a

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [6]:
a < 10

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]], dtype=bool)

In [7]:
choose(a<10, (a,10))

array([[10, 10, 10],
       [10, 11, 12],
       [20, 21, 22]])

In [9]:
shape(choose(a<10, (a,10)))

(3, 3)

### Clip lower and upper values

In [10]:
lt = a < 10
gt = a > 15
choice = lt + 2 * gt
choice

array([[1, 1, 1],
       [0, 0, 0],
       [2, 2, 2]])

In [11]:
choose(choice, (a, 10, 15))

array([[10, 10, 10],
       [10, 11, 12],
       [15, 15, 15]])

Copyright 2008-2016, Enthought, Inc.<br>Use only permitted under license.  Copying, sharing, redistributing or other unauthorized use strictly prohibited.<br>http://www.enthought.com