# General Function Review

In [2]:
# Imports required but not shown in the video lecture.
from numpy import array, inf, nan, isinf, arange, isnan, cumsum

## Trig and Other Functions (see video)

## More Basic Functions (see video)

### Live Demo (starting @ 3:04 in video)

In [3]:
inf

inf

In [4]:
-inf

-inf

In [5]:
nan

nan

In [6]:
isinf(inf)

True

In [7]:
isinf(1.0)

False

In [8]:
isinf(-inf)

True

In [9]:
1.0 == inf

False

In [10]:
inf == inf

True

In [11]:
nan

nan

In [12]:
array([0])

array([0])

In [13]:
a = array([0])

In [14]:
a / 0.0

/home/wangweiyi/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in divide
  if __name__ == '__main__':


array([ nan])

In [15]:
0.0 / 0.0

ZeroDivisionError: float division by zero

In [16]:
a = arange(5.0)

In [17]:
a

array([ 0.,  1.,  2.,  3.,  4.])

In [18]:
b = a / 0.0

/home/wangweiyi/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in divide
  if __name__ == '__main__':
/home/wangweiyi/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in divide
  if __name__ == '__main__':


In [19]:
b

array([ nan,  inf,  inf,  inf,  inf])

In [20]:
b == nan

array([False, False, False, False, False], dtype=bool)

In [21]:
isnan(b)

array([ True, False, False, False, False], dtype=bool)

### Back to Slide (@ 6:08 in video)

### Live Demo (@ 7:34 in video)

In [22]:
a

array([ 0.,  1.,  2.,  3.,  4.])

In [23]:
cumsum(a)

array([  0.,   1.,   3.,   6.,  10.])

Copyright 2008-2016, Enthought, Inc.<br>Use only permitted under license.  Copying, sharing, redistributing or other unauthorized use strictly prohibited.<br>http://www.enthought.com