# Matrix Objects

In [1]:
# Imports required but not shown in the video lecture.
from numpy import array, mat, bmat

## Matrix Objects
### Matrix creation

Converting an array to a matrix.

In [2]:
a = array([[1, 2, 4],
           [2, 5, 3],
           [7, 8, 9]])
A = mat(a)
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

Matlab-like creation from string.

In [3]:
A = mat('1, 2, 4; 2, 5, 3; 7, 8, 9')
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

## Matrix Objects
### Block matrices

Create a matrix from sub-matrices.

In [4]:
a = array([[1, 2],
           [3, 4]])
b = array([[10, 20],
           [30, 40]])
bmat('a, b; b, a')

matrix([[ 1,  2, 10, 20],
        [ 3,  4, 30, 40],
        [10, 20,  1,  2],
        [30, 40,  3,  4]])

## Matrix Objects
### Matrix multiply

In [5]:
A = mat([[1, 2, 4],
         [2, 5, 3],
         [7, 8, 9]])
x = array([[1], [2], [3]])
x

array([[1],
       [2],
       [3]])

Matrix multiply

In [6]:
A*x

matrix([[17],
        [21],
        [50]])

Matrix identity

In [28]:
%precision %i
A.I

matrix([[-0.4, -0.3,  0.3],
        [-0.1,  0.4, -0.1],
        [ 0.4, -0.1, -0. ]])

In [31]:
%precision %i
A*A.I

matrix([[  1.0e+00,   0.0e+00,   0.0e+00],
        [  0.0e+00,   1.0e+00,   6.2e-17],
        [  2.2e-16,  -8.3e-17,   1.0e+00]])

### Matrix exponent

In [8]:
A**4

matrix([[ 6497,  9580,  9836],
        [ 7138, 10561, 10818],
        [18434, 27220, 27945]])

Copyright 2008-2016, Enthought, Inc.<br>Use only permitted under license.  Copying, sharing, redistributing or other unauthorized use strictly prohibited.<br>http://www.enthought.com