# Creating Grids of Numbers

In [1]:
# Imports required but not shown in the video lecture.
import matplotlib.pyplot as plt
from matplotlib.pyplot import imread, imshow, plot, title, axis, xlabel, ylabel, cm
from mpl_toolkits.mplot3d import Axes3D

from numpy import array, linspace, meshgrid, sqrt, sin, seterr

seterr(divide='ignore', invalid='ignore')
%matplotlib inline


## Evaluating a Function on a Grid (see video)
## Evaluation Grid (see video)
## `meshgrid` (notebook starts  @ 2:52 in video)

In [5]:
def f(x, y):
    # The sinc function.
    r = sqrt(x**2 + y**2)
    result = sin(r)/r
    result[r==0] = 1.0
    return result

Create grid points.

In [2]:
x_ticks = linspace(-1, 1, 5)
y_ticks = linspace(-1, 1, 5)
x, y = meshgrid(x_ticks, y_ticks)

In [3]:
x

array([[-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ]])

In [4]:
y

array([[-1. , -1. , -1. , -1. , -1. ],
       [-0.5, -0.5, -0.5, -0.5, -0.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0.5,  0.5,  0.5,  0.5,  0.5],
       [ 1. ,  1. ,  1. ,  1. ,  1. ]])

In [6]:
x_ticks = linspace(-10, 10, 51)
y_ticks = linspace(-10, 10, 51)
x, y = meshgrid(x_ticks, y_ticks)

Evaluate `z`, given `x` and `y`.

In [7]:
z = f(x, y)

In [8]:
z

array([[ 0.07070981,  0.06942837,  0.06278079, ...,  0.06278079,
         0.06942837,  0.07070981],
       [ 0.06942837,  0.06237817,  0.05016709, ...,  0.05016709,
         0.06237817,  0.06942837],
       [ 0.06278079,  0.05016709,  0.03304271, ...,  0.03304271,
         0.05016709,  0.06278079],
       ..., 
       [ 0.06278079,  0.05016709,  0.03304271, ...,  0.03304271,
         0.05016709,  0.06278079],
       [ 0.06942837,  0.06237817,  0.05016709, ...,  0.05016709,
         0.06237817,  0.06942837],
       [ 0.07070981,  0.06942837,  0.06278079, ...,  0.06278079,
         0.06942837,  0.07070981]])

And plot it in 3 dimensions.

In [11]:
%matplotlib
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(x, y, z,
                rstride=1, cstride=1,
                cmap=cm.YlGnBu_r)
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')

Using matplotlib backend: Qt4Agg


## `meshgrid`: Sparse Option

Create grid points.

In [ ]:
x_ticks = linspace(-10, 10, 51)
y_ticks = linspace(-10, 10, 51)
x, y = meshgrid(x_ticks, y_ticks,
                sparse=True)

In [ ]:
x

In [ ]:
y

Create grid points.

In [ ]:
x_ticks = linspace(-10, 10, 51)
y_ticks = linspace(-10, 10, 51)
x, y = meshgrid(x_ticks, y_ticks,
                sparse=True,
                indexing='ij')

In [ ]:
x

In [ ]:
y

## `meshgrid`: Indexing (see video)

Copyright 2008-2016, Enthought, Inc.<br>Use only permitted under license.  Copying, sharing, redistributing or other unauthorized use strictly prohibited.<br>http://www.enthought.com