# Ones, Zeros, and Empty

In [1]:
# Imports required but not shown in the video lecture.
from numpy import (ones, zeros, empty, float32, arange, 
                   empty_like, ones_like, zeros_like, identity)

## Array Creation Functions
### `ones`, `zeros`

```python
ones(shape, dtype=float64)
zeros(shape, dtype-float64)
```

`shape` is a number or sequence specifying the dimensions of the array. If `dtype` is not specified, it defaults to `float64`.

In [2]:
ones((2, 3), dtype=float32)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

In [ ]:
zeros(3)

### Live Demo

In [ ]:
ones((2, 3))

In [3]:
ones((2, 3)) * 5

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

### Back to Slide

## Array Creation Functions (cont.)
### `empty` and `fill`

```python
empty(shape, dtype=float64, order='C')
```

In [4]:
a = empty(2)
a

array([  0.00000000e+00,   6.52072821e+91])

Fill array with 5.0

In [5]:
a.fill(5.0)
a

array([ 5.,  5.])

Alternative approach (slightly slower)

In [6]:
a[:] = 4.0
a

array([ 4.,  4.])

### Live Demo

In [8]:
a = arange(5, dtype=float32)
a

array([ 0.,  1.,  2.,  3.,  4.], dtype=float32)

In [10]:
b = empty_like(a)
b

array([ 0.,  0.,  0.,  0.,  0.], dtype=float32)

In [11]:
b = ones_like(a)
b

array([ 1.,  1.,  1.,  1.,  1.], dtype=float32)

In [12]:
b = zeros_like(a)
b

array([ 0.,  0.,  0.,  0.,  0.], dtype=float32)

### Back to Slide

## Identity Function
### `identity`

Generate an n by n identity array. The default type is float64.

In [13]:
a = identity(4)
a

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [ ]:
a.dtype

In [14]:
identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

Copyright 2008-2016, Enthought, Inc.<br>Use only permitted under license.  Copying, sharing, redistributing or other unauthorized use strictly prohibited.<br>http://www.enthought.com