# Structured Arrays

In [1]:
# Imports required but not shown in the video lecture.
from numpy import array, int64, float32, complex64, dtype, empty

## "Structured Arrays" 

Declare your own dtype for a NumPy array. (starts @ 2:30 in video)

In [2]:
a = array([1.0, 2.0, 3.0, 4.0], dtype=float32)

In [3]:
a

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [4]:
a.view(complex64)

array([ 1.+2.j,  3.+4.j], dtype=complex64)

Declare your own `dtype` for a NumPy array.

In [5]:
particle_dtype = dtype([('mass', 'float32'),
                        ('velocity', 'float32')])

a.view(particle_dtype)


array([(1.0, 2.0), (3.0, 4.0)], 
      dtype=[('mass', '<f4'), ('velocity', '<f4')])

## Working with a Structured Array
"Data structure" (dtype) that describes the fields and type of the items in each array element.

In [ ]:
particle_dtype = dtype([('mass', 'float32'),
                        ('velocity', 'float32')])

The items converted to particles must be a list of tuples.

In [6]:
particles = array([(1, 1), (1, 2), (2, 1), (1, 3)],
                  dtype=particle_dtype)

print particles

[(1.0, 1.0) (1.0, 2.0) (2.0, 1.0) (1.0, 3.0)]


Retrieve particle 0 through indexing.

In [7]:
particles[0]

(1.0, 1.0)

Retrieve the mass for all particles through indexing.

In [8]:
print particles['mass']

[ 1.  1.  2.  1.]


Sort particles in place, with velocity as the primary field and mass as the secondary field.

In [9]:
particles.sort(order=('velocity', 'mass'))
print particles

[(1.0, 1.0) (2.0, 1.0) (1.0, 2.0) (1.0, 3.0)]


## Declaration Format
### Endianness

"Data structure" (dtype) that describes the fields and type of the items in each array element.

In [ ]:
particle_dtype = dtype([('mass', 'float32'),
                        ('velocity', 'float32')])

A 'float32' field is displayed as a '<f4'. The '<' means little endian, and the f4 is a four byte float.

In [ ]:
particle_dtype

### Equivalent field type declarations
Using strings for field type definitions with bit specification.

In [ ]:
particle_dtype = dtype([('mass', 'float32'),
                        ('velocity', 'float32')])

Using NumPy dtypes for field type definition.

In [ ]:
particle_dtype = dtype([('mass', float32),
                        ('velocity', float32)])

Using strings for field type definitions with byte specification.

In [ ]:
particle_dtype = dtype([('mass', 'f4'),
                        ('velocity', 'f4')])

## Mixed Data Types
### Mixed data types

Structured data format.

In [11]:
person_dtype = dtype([('name', 'S10'),
                      ('age', int),
                      ('weight', float)])

Each person requires 26 bytes of space.

In [12]:
person_dtype.itemsize

26

Create an empty 2-D array of people.

In [14]:
people = empty((3, 4), dtype=person_dtype)

Fill in the fields with data.

In [15]:
people['name'] = [['Brad', 'Jane', 'John', 'Fred'],
                  ['Henry', 'George', 'Brian', 'Amy'],
                  ['Ron', 'Susan', 'Jennifer' , 'Jill']]
people['age'] = [[33, 25, 47, 54], 
                 [29, 61, 32, 27], 
                 [19, 33, 18, 54]]
people['weight'] = [[135, 105, 225, 140], 
                    [154, 202, 137, 187], 
                    [188, 135, 88, 145]]
print people

[[('Brad', 33, 135.0) ('Jane', 25, 105.0) ('John', 47, 225.0)
  ('Fred', 54, 140.0)]
 [('Henry', 29, 154.0) ('George', 61, 202.0) ('Brian', 32, 137.0)
  ('Amy', 27, 187.0)]
 [('Ron', 19, 188.0) ('Susan', 33, 135.0) ('Jennifer', 18, 88.0)
  ('Jill', 54, 145.0)]]


Accessing a singe array element. (A particular person)

In [16]:
people[0, 0]

('Brad', 33, 135.0)

In [ ]:
people[-1, -1]

Accessing all the name at one time.

In [ ]:
people['name']

Copyright 2008-2016, Enthought, Inc.<br>Use only permitted under license.  Copying, sharing, redistributing or other unauthorized use strictly prohibited.<br>http://www.enthought.com